### PR TITLE
Support LiveView 0.19 and Live Dashboard 0.8

### PR DESCRIPTION
**Pull request by filipecabaco**
Makes the required changes to make it work with live_dashboard 0.8 and live_view 0.19.

Also removes ETS as an external dependency.

### CODE REVIEW

**Comment by bcardarella** [comment]
@TheFirstAvenger ping on this. We should just look toward LiveView v0.20

**Comment by TheFirstAvenger** [comment]
@filipecabaco v0.6.0 is now available with support for LiveView 0.20.

**Comment by lessless** [comment]
fantastic, thanks 🥳

**Comment by bcardarella** [comment]
With LiveView nearing 1.0 I hope we're getting to a place of stability

**Pull request closed without merging**
